// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "gen-cpp/helloSvc.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class helloSvcHandler : virtual public helloSvcIf {
 public:
  helloSvcHandler() {
    // Your initialization goes here
  }

  void getMessage(std::string& _return, const std::string& name) {
    // Your implementation goes here
    printf("getMessage\n");
    _return = "hello " + name;
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<helloSvcHandler> handler(new helloSvcHandler());
  ::std::shared_ptr<TProcessor> processor(new helloSvcProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

